// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdnzcwsrhaqhazhcybuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkbnpjd3NyaGFxaGF6aGN5YnVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NzU4NjEsImV4cCI6MjA2OTU1MTg2MX0.bvBrH2oHXP7jnPmwGHwt4JtfATsF-quEyHnUKEQGilk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});